[[bowtie]]
arch = "aarch64"
git-tree-sha1 = "00a3c3e8540f3a6748cbb2f69e5b82eb9751a537"
os = "macos"

    [[bowtie.download]]
    sha256 = "51c80775735ac46eadf6e6ac8edfe1a32da92d5faba24f29cadcf138ff9fc0c9"
    url = "https://github.com/JuliaBinaryWrappers/bowtie_jll.jl/releases/download/bowtie-v2.5.1+0/bowtie.v2.5.1.aarch64-apple-darwin.tar.gz"
[[bowtie]]
arch = "x86_64"
git-tree-sha1 = "76eb3c5e501bce3de32cd08e0b5b7c84e8b28a2e"
os = "macos"

    [[bowtie.download]]
    sha256 = "79747f3cbe42fa6fe7156e18b243e65ef5dda093ef8e8d3ca0f2b8c016941b01"
    url = "https://github.com/JuliaBinaryWrappers/bowtie_jll.jl/releases/download/bowtie-v2.5.1+0/bowtie.v2.5.1.x86_64-apple-darwin.tar.gz"
[[bowtie]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1bcee4830b1b70c5f9f9234ba9104f50121ffb9"
libc = "glibc"
os = "linux"

    [[bowtie.download]]
    sha256 = "fddd26a90726a4840847e1849fd8ef6c4b9ec134cef5f4a36b671103e2335b9e"
    url = "https://github.com/JuliaBinaryWrappers/bowtie_jll.jl/releases/download/bowtie-v2.5.1+0/bowtie.v2.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[bowtie]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d1b91b437ab40b12d393805a8054d6120e5df22"
libc = "glibc"
os = "linux"

    [[bowtie.download]]
    sha256 = "5dfdb74081a7ecd790d9e87200aca426f4cd32831ae1f30ba14a2ea57e43519f"
    url = "https://github.com/JuliaBinaryWrappers/bowtie_jll.jl/releases/download/bowtie-v2.5.1+0/bowtie.v2.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[bowtie]]
arch = "x86_64"
git-tree-sha1 = "240db84091201a6ae1b798eddcffdc9fc36428c5"
os = "freebsd"

    [[bowtie.download]]
    sha256 = "9cff96f5310b75082378b6bcfc9c7a9a2ea6a4392553734d7b505cadd210b2be"
    url = "https://github.com/JuliaBinaryWrappers/bowtie_jll.jl/releases/download/bowtie-v2.5.1+0/bowtie.v2.5.1.x86_64-unknown-freebsd.tar.gz"
