# Autogenerated wrapper script for bowtie_jll for x86_64-linux-gnu-cxx11
export bowtie2, bowtie2_align_l, bowtie2_align_s, bowtie2_build, bowtie2_build_l, bowtie2_build_s, bowtie2_inspect, bowtie2_inspect_l, bowtie2_inspect_s

using Zlib_jll
JLLWrappers.@generate_wrapper_header("bowtie")
JLLWrappers.@declare_executable_product(bowtie2)
JLLWrappers.@declare_executable_product(bowtie2_align_l)
JLLWrappers.@declare_executable_product(bowtie2_align_s)
JLLWrappers.@declare_executable_product(bowtie2_build)
JLLWrappers.@declare_executable_product(bowtie2_build_l)
JLLWrappers.@declare_executable_product(bowtie2_build_s)
JLLWrappers.@declare_executable_product(bowtie2_inspect)
JLLWrappers.@declare_executable_product(bowtie2_inspect_l)
JLLWrappers.@declare_executable_product(bowtie2_inspect_s)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_executable_product(
        bowtie2,
        "bin/bowtie2",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_align_l,
        "bin/bowtie2-align-l",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_align_s,
        "bin/bowtie2-align-s",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_build,
        "bin/bowtie2-build",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_build_l,
        "bin/bowtie2-build-l",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_build_s,
        "bin/bowtie2-build-s",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_inspect,
        "bin/bowtie2-inspect",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_inspect_l,
        "bin/bowtie2-inspect-l",
    )

    JLLWrappers.@init_executable_product(
        bowtie2_inspect_s,
        "bin/bowtie2-inspect-s",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
